apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: python-unittest
  namespace: testflask-cicd
spec:
  description: This task can be used to run unit tests for python.
  params:
    - default: latest
      description: "The used Python version, more precisely the tag for the Python image"
      name: PYTHON
      type: string
    - default: ""
      description: The additional arguments to be used with unittest
      name: ARGS
      type: string
    - default: test.py
      description: Name of test file
      name: TEST_FILE
      type: string
    - default: requirements.txt
      description: The name of the requirements file inside the source location
      name: REQUIREMENTS_FILE
      type: string
    - default: .
      description: The path to the source code
      name: SOURCE_PATH
      type: string
  steps:
    - image: "docker.io/python:$(inputs.params.PYTHON)"
      name: python-unittest
      resources: {}
      script: |
        export PATH=$PATH:$HOME/.local/bin

        pip install -r $(inputs.params.REQUIREMENTS_FILE)
        python $(inputs.params.TEST_FILE) || echo "unittest Failed"
      workingDir: $(workspaces.output.path)/$(inputs.params.SOURCE_PATH)
  workspaces:
    - name: output
